global:
  rbac:
    create: true

grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.k8s.mcapala.pl
    image:
      tag: "11.0.0"
  persistence:
    enabled: true
    size: 5Gi

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.k8s.mcapala.pl
  retention: 3d
  prometheusSpec:
    retention: 5d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi